### ISSUE TITLE
weather-darksky.tcl 

### ISSUE THREAD

**Issue by reelated** [horgh/eggdrop-scripts#10]
Hi, I am getting a error of "Error looking up latitude/longitude: HTTP status 401" when trying to use the script. Any ideas? I'm guessing it has something to do with credentials.

**Comment by reelated** [comment]
UPDATE: I enables the free webservices and now and getting 
"Tcl error [::wds::lookup_current]: can't read "key": no such variable"
I will troubleshoot more.

**Comment by reelated** [comment]
All set, I goofed something up in the script. Thanks for the cool scripts, horgh.
Please close this issue.

**Comment by horgh** [comment]
Cool, glad you got it working!
