### ISSUE TITLE
Error: key "Location" not known in dictionary

### ISSUE THREAD

**Issue by koustab** [horgh/eggdrop-scripts#12]
hi there

im using the same script today i spotted an issue. when im trying to look for works like twat / f its giving me the following error Error: key "Location" not known in dictionary

but then again when im searching for Twat it pulls out results. what can be the possible reason?

**Comment by horgh** [comment]
It looks like there was a change on the urbandictionary site, together with a bug in the script. I pushed a fix: https://github.com/horgh/eggdrop-scripts/commit/8e6992f9a228e94ac15a468584840ee968199e9f. Thanks for reporting it!
