### ISSUE TITLE
Slang.tcl Issues

### ISSUE THREAD

**Issue by webheaded** [horgh/eggdrop-scripts#7]
I've seen this with a few Urban Dictionary scripts now but the slang.tcl script is not working at all currently.  I try !slang anything and I get nothing back at all.  Not sure if the API changed or it's something with the website in general (someone else mentioned they use Cloudflare now).

**Comment by horgh** [comment]
That's interesting. I just tried it on my bot and it works okay.

Would you be able to enable the `store_responses` option in the script and paste what you're getting back somewhere? I wonder if as you say Cloudflare is blocking you for some reason (I have no idea if Urbandictionary changed anything). Also, is there anything showing in the bot's logs when you make a request?

**Comment by webheaded** [comment]
Okay I actually figure out 2 things here.

First off, I'm an idiot and didn't realize the trigger was just "slang" rather than !slang or !ud so I fixed that.

Then I started getting errors telling me **Error: Unsupported URL type "https"** most likely because the site forces HTTPS.  I made sure to install the tcltls package but it still said the same thing.  I found another script that registered https at the beginning with the following lines:

```
package require tls 
http::register https 443 [list ::tls::socket -require 0 -request 1] 
```

Put those lines in underneath the require http line and bam, it works now.  I'm actually perplexed at how yours was working with that going on but I think I've got it fixed now. :D

**Comment by horgh** [comment]
Nice! Yeah, that dependency & register call should be put in the script. Thanks for finding that!

Regarding how it worked for me: Likely a different script included tls and registered the port on my bot. It is something global so if one script does it then it works for all.

**Comment by koustab** [comment]
hi im using the same script. it was wroking find but today i find out an issue.
when im looking for  some or the word its giving me this error Error: key "Location" not known in dictionary

what possible the reason?

thanks

**Comment by angelperezleon** [comment]
In twitoauth.tcl you have the below code
 #Only enable TLSv1
 #below from https://github.com/horgh/eggdrop-scripts/issues/7#issuecomment-362717835

I like to extend this to only enabling TLSv1.1 or TLSv1.2, so added this below so know how to query for the versions i have enabled for example on a Debian 10 - Buster OS
```
# How to show all available tls version on raspberry pi:
#  openssl ciphers -v | awk '{print $2}' | sort | uniq
```

Good example output below , seen below.
Which leads me to plug the holes and disable SSLv3 at the very least & even TLSv1 if nothing else is affected by the eggdrop functionality.  running eggdrop v1.8.4
```
pi@pi:~ $ openssl ciphers -v | awk '{print $2}' | sort | uniq
SSLv3
TLSv1
TLSv1.2
TLSv1.3
```

**Comment by angelperezleon** [comment]
further more to the above:

I have this under:  /etc/ssl/openssl.cnf
```
[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT@SECLEVEL=2
```
