### ISSUE TITLE
weather-darksky.tcl

### ISSUE THREAD

**Issue by sacredland** [horgh/eggdrop-scripts#9]
hello, ive get the geonames.tcl & darksky.tcl, also have the .conf file, but eggdrop still gave me Error looking up latitude/longitude: no results found. I would like to know how to get that working?

**Comment by horgh** [comment]
Did you create an account on www.geonames.org and set the username in the config to that?

What are you querying? I know "vancouver" works for example.

Can you edit geonames.tcl to print out what `$response` is inside the `if` on line 36? You could probably add a `putlog $response`. That may tell us what's going wrong.

**Comment by sacredland** [comment]
yes i created an account and the username into weather-darksky.conf,

<tabb> .wz vancouver
<kingdom> Error looking up latitude/longitude: no results found

line 36: 
	if {![dict exists putlog $response geonames]} {
		return [dict create error "no results found"]
	}

**Comment by horgh** [comment]
If you change that to this:

```tcl
if {![dict exists putlog $response geonames]} {
    return [dict create error $response]
}
```

And run a lookup, can you tell me what it says?

**Comment by sacredland** [comment]
kingdom> Error looking up latitude/longitude: status {message {user account not enabled to use the free webservice. Please enable it on your account page: http://www.geonames.org/manageaccount } value 10}

so, i enabled it. tried it:

.wz vancouver
[19:33:01] <kingdom> Error looking up latitude/longitude: totalResultsCount 848 geonames {{adminCode1 02 lng -123.11934 geonameId 6173331 toponymName Vancouver countryId 6251999 fcl P population 600000 countryCode CA name Vancouver fclName {city, village,...} adminCodes1 {ISO3166_2 BC} countryName Canada fcodeName {populated place} adminName1 {British Columbia} lat 49.24966 fcode PPL} {adminCode1 WA lng -122.66149 geonameId 5814616 toponymName Vancouver countryId 6252001

so i put back on line 37  "no results found" instead of $response and
.wz vancouver
[19:34:30] <kingdom> Error looking up latitude/longitude: no results found

**Comment by horgh** [comment]
The `$response` that you printed out (`[19:33:01] Error looking up latitude/longitude: totalResultsCount 848 geonames {{adminCode1 02[etc]`) looks like a successful lookup. So that's good.

What does your line 36 look like now? I wonder if there's a change - it should not include putlog. I see above you had it like this `if {![dict exists putlog $response geonames]} {`. The `putlog` in it should not be present. It should be: `if {![dict exists $response geonames]} {`

**Comment by sacredland** [comment]
if {![dict exists $response geonames]} {
                return [dict create error "no results found"]
        }

but if i do a .wz vancouver, in partyline i got 
[20:45:47] <(s)kingdom> [20:45:47] Tcl error [::wds::lookup_current]: can't read "key": no such variable

**Comment by horgh** [comment]
Hmm, I don't see any use of $key that would cause that error unfortunately.

Have you made any other changes to the scripts? Maybe you could run a diff of them against the ones from the repo.

Alternatively you could add putlog calls to debug at what line the error occurs and that might help us figure it out. e.g. adding one before the call to `::wds::get_data` and one after, and if we only see the first log message, then we'd know it's happening in `::wds::get_data`.

**Comment by sacredland** [comment]
i have re-clone the rep and now it work. 

thanks for you help, it's appreciated

**Comment by horgh** [comment]
Nice!
